### ISSUE TITLE
RFC: Have a config file for cargo-generate?

### ISSUE THREAD

**Issue by killercup** [ashleygwilliams/cargo-generate#48]
## Context

When cargo-generate tries to generate a project, it may require meta-information, e.g. which placeholders to look for, or how to find files to apply substitutions to. While currently, this is defined by hard-coded rules in the tool itself, in the future this might be configurable.

## Questions

Should templates be able to contain (optional) config files to pass parameters and meta information to cargo-generate?

## Possibles solutions

- Yes, and it'll be in TOML format with a schema like

    ```toml
    [template]
    name = "foo"
    repository = "https://github.com/rust-lang-nursery/cargo-template-foo"
    placeholders = ["project-name", "author"]
    ```

- Yes, and it can also be a subsection of a `Cargo.toml` file
- Yes, and it can also be a subsection of a `book.toml` file
- No
